version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - vayu-otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.83.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
    networks:
      - vayu-otel-network

networks:
  vayu-otel-network:
    driver: bridge
